services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    environment:
      DB_PASS: /run/secrets/db_pass
      SECRET_KEY: /run/secrets/secret_key
    secrets:
      - db_pass
      - secret_key
    depends_on:
      mariadb:
        condition: service_started
        restart: true

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_pass
      MARIADB_DATABASE: webapp
    ports:
      - "127.0.0.1:3306:3306"
    secrets:
      - db_pass
    volumes:
      - "./db:/var/lib/mysql"

secrets:
  db_pass:
    file: pass
  secret_key:
    file: key 