services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    environment:
      DB_PASS: /run/secrets/db_pass
      SECRET_KEY: /run/secrets/secret_key
    secrets:
      - db_pass
      - secret_key

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pass
      MYSQL_DATABASE: app
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
    secrets:
      - db_pass

secrets:
  db_pass:
    file: pass
  secret_key:
    file: key 